apiVersion: apps/v1
kind: Deployment
metadata:
  name: devhubtest
  labels:
    app.kubernetes.io/name: devhubtest
    kubernetes.azure.com/generator: devhub
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: devhubtest
  template:
    spec:
      containers:
        - name: devhubtest
          image: go-http-hello-world:latest