apiVersion: v1
kind: Service
metadata:
  name: go-http-hello-world
  namespace: default
  labels:
    app.kubernetes.io/name: go-http-hello-world
    kubernetes.azure.com/generator: draft
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: go-http-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80