apiVersion: v1
kind: Service
metadata:
  name: devhubApp
  namespace: default
  labels:
    app.kubernetes.io/name: devhubApp
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: devhubApp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080